apiVersion: apps/v1
kind: Deployment
metadata:
  name: licence-manager-deployment
  namespace: sx-licence-manager
  labels:
    app: licence-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: licence-manager
  template:
    metadata:
      labels:
        app: licence-manager
    spec:
      containers:
        - name: licence-manager
          image: licencemanageracr.azurecr.io/licence-manager:latest
          ports:
          - containerPort: 80
          env:
            # - name: MSSQL_PID
            #   value: "Developer"
            # - name: ACCEPT_EULA
            #   value: "Y"
            # - name: SA_PASSWORD
            #   value: VG91Z2hwYXNzMSE=
            # - name: ME_CONFIG_SQL_SERVER
            #   valueFrom: 
            #     configMapKeyRef:
            #       name: mssql-config
            #       key: mssql.conf
            # - name: servicename_SERVICE_HOST
            #   value: mssql-latest-deploy
      imagePullSecrets:
        - name: licence-manager-acrsecret

---
apiVersion: v1
kind: Service
metadata:
  name: licence-manager-service
  namespace: sx-licence-manager
spec:
  selector:
    app: licence-manager
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      

